#!/bin/bash

docker stop webserver
docker rm webserver

docker stop app
docker rm app
docker rmi openweb/php:5.4
docker rmi openweb/php:5.6
docker rmi openweb/php:7.0
docker rmi openweb/php:7.1
docker rmi openweb/php:7.2
docker rmi openweb/php:7.3
docker rmi openweb/php:7.4

docker stop mysql
docker rm mysql

docker stop pgsql
docker rm pgsql

docker stop redis
docker rm redis

docker stop rabbitmq
docker rm rabbitmq